[package]
name = "swiss-knife"
authors = ["Michalis Molfetas"]
version = "1.1.1"
edition = "2024"

[dependencies]

# GUI
egui = "0.36"
eframe = {version = "0.36", features = ["wgpu"]}
egui_extras = { version = "0.36", features = ["image"] }
egui-elegance = "0.15"
zeus-theme = "0.4"
zeus-widgets = "0.4"
zeus-ui-components = {version = "0.4", features = ["secure-types", "qr-scanner"]}

# Crypto
sha3 = "0.12"
hmac = {version = "0.13.0", features = ["zeroize"]}
hybrid-array = {version = "0.4.14", features = ["zeroize"]}
hex = "0.4"
ncrypt-me = "0.3"

# Misc
rfd = "0.17"
lazy_static = "1"

[profile.prod]
inherits = "release"
codegen-units = 1
incremental = true
strip = true
opt-level = 2
debug = false
lto = "fat"